package com.sharifin.retrofit

const val NO_ENCRYPTION_VALUE = "false"
const val NO_DECRYPTION_HEADER = "Decrypt"
const val NO_DECRYPTION_VALUE = "false"
const val NO_ENCRYPTION_HEADER = "Encrypt"
const val NO_ENCRYPTION_NEEDED = "$NO_ENCRYPTION_HEADER: $NO_ENCRYPTION_VALUE"
const val NO_DECRYPTION_NEEDED = "$NO_DECRYPTION_HEADER: $NO_DECRYPTION_VALUE"
